### ISSUE TITLE
Chapter 2 section 4 has a repeated sentence.

### ISSUE THREAD

**Issue by SebastianAmyotte** [fitz/debuggingteams#1]
In chapter 2, Building an Awesome Team Culture, section 4, Communication Patterns of Successful Cultures:

The first immediate phrase, "Communication can often be a challenge when you’re working with a team," is repeated twice.

https://book.debuggingteams.com/#communication_patterns_of_successful_cul

**Comment by fitz** [comment]
Thank you!

**Comment by sussman** [comment]
FIxed in change 273ca1fc7aa7da195288cf23603efd9a762a5977
